version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-net
    env_file:
      - .env
    depends_on:
      - my-db
      - redis

  frontend:
    build:
      context: ./src/main/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-net
    depends_on:
      - backend

  my-db:
    image: postgres
    container_name: my-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: account_book
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
