services:
  app:
    build: .
    container_name: my-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - my-db
      - redis
  my-db:
    container_name: my-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: account_book
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
