services:
  my-db:
    container_name: my-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: account_book
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
