spring:
  application:
    name: account-book
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  refresh:
    secret: ${JWT_REFRESH_SECRET}

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
